Update sync-neovim.yml

diff --git a/.github/workflows/sync-neovim.yml b/.github/workflows/sync-neovim.yml
--- a/.github/workflows/sync-neovim.yml
+++ b/.github/workflows/sync-neovim.yml
@@ -37,7 +37,7 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub 自动提供
         run: |
           # 检查是否已有相同 tag 的 Release
-          existing_release=$(gh release view "$release_tag" || echo "not found")
+          existing_release=$(gh release view "$release_tag" --json name || echo "not found")
           
           # 如果没有相同 tag，则创建新的 Release
           if [[ "$existing_release" == "not found" ]]; then
